/**
 * fonts.ts — central font registration for the @react-pdf/renderer pipeline.
 *
 * E6.5 Task 5.2 — single source of truth for PDF font registration. Every
 * module under `src/lib/pdf/` that needs branded type imports `registerPdfFonts()`
 * and calls it once; the helper is idempotent (`@react-pdf/font`'s internal
 * registry is keyed by family + variant + src, so duplicate calls are no-ops).
 *
 * ----------------------------------------------------------------------------
 * Why this exists (Task 5.1 spike finding #1 — CRITICAL)
 * ----------------------------------------------------------------------------
 *
 * The brand woff2 files in `public/fonts/` are pre-subset latin-only files
 * (~15-18 KB each) generated by `@fontsource/montserrat` /
 * `@fontsource/source-sans-3` for browser delivery. `fontkit` (the font
 * engine inside `@react-pdf/renderer`) CANNOT re-subset those woff2 files —
 * it crashes in `TTFSubset._addGlyph` with `RangeError: Offset is outside
 * the bounds of the DataView`. The PDF pipeline therefore registers the
 * **unsubset** TTF source files under `public/fonts/pdf/` instead. Those
 * files are documented + licensed in `public/fonts/pdf/README.md`.
 *
 * ----------------------------------------------------------------------------
 * Why bare absolute filesystem paths (Task 5.1 spike finding #3)
 * ----------------------------------------------------------------------------
 *
 * `@react-pdf/font`'s `FontSource._load()` runs `isUrl(src)` and routes any
 * URL-shaped input through `fetch()`. Node's undici fetch does not implement
 * the `file://` scheme — it throws `not implemented... yet...`. A bare
 * absolute filesystem path skips the URL branch and hits `fontkit.open(src)`
 * directly. We therefore resolve paths via `path.resolve(process.cwd(),
 * 'public', 'fonts', 'pdf', name)` — never via `pathToFileURL()`.
 *
 * `process.cwd()` is the Next.js project root (`website/`) in every context
 * this module runs: `npm run dev`, `npm run build`, the serverless function
 * runtime (`/var/task/` after deployment), vitest. Next.js documents the
 * `process.cwd()` contract at https://nextjs.org/docs/messages/dependency-not-found.
 *
 * ----------------------------------------------------------------------------
 * Spec / family naming (spec v0.5 substitution — OQ pending close)
 * ----------------------------------------------------------------------------
 *
 * `Family.register({ family: 'Source Sans 3' })` — NOT `'Source Sans Pro'`.
 * Spec §5.1 substituted Source Sans Pro → Source Sans 3 in v0.5 (2026-05-31).
 * Adobe shipped the family rename in 2021; SS3 is the current canonical name.
 */

import { Font } from '@react-pdf/renderer';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';

/**
 * Build an absolute filesystem path to a TTF in `public/fonts/pdf/`.
 *
 * Throws synchronously at module load time (when `registerPdfFonts` is
 * called) if the file is missing — earlier is better than a runtime fontkit
 * crash mid-PDF-render. The error message points at the README.md so the
 * reader knows the fix is to re-run the canonical download steps.
 */
function pdfFontPath(filename: string): string {
  const abs = resolve(process.cwd(), 'public', 'fonts', 'pdf', filename);
  if (!existsSync(abs)) {
    throw new Error(
      `[lib/pdf/fonts] PDF font file not found: ${abs}\n` +
        `Expected unsubset TTF — see website/public/fonts/pdf/README.md for ` +
        `the canonical download URLs and re-add the file.`,
    );
  }
  return abs;
}

/**
 * Idempotent registry call. Safe to invoke from any module in `lib/pdf/`;
 * `@react-pdf/font` deduplicates by (family, weight, style, src). Modules
 * are encouraged to call this at the top of their file — once at module
 * load, never inside a component render path.
 *
 * Registration intentionally narrows the per-family weight set to the
 * minimum E6.5 requires. Adding a new weight (e.g. Source Sans 3 Light)
 * requires both (a) a new TTF in `public/fonts/pdf/` and (b) a new entry
 * in the `fonts` array here.
 */
let registered = false;

export function registerPdfFonts(): void {
  if (registered) return;

  // Montserrat — used for the report title in the Letterhead and for
  // section headings inside PDF templates (E6.6). SemiBold only — body
  // and caption sizes use Source Sans 3.
  Font.register({
    family: 'Montserrat',
    fonts: [{ src: pdfFontPath('Montserrat-SemiBold.ttf'), fontWeight: 600 }],
  });

  // Source Sans 3 — used for body, captions, timestamps, footer copy.
  // Regular (400) + Semibold (600) only. No italic ships — see Task 5.1
  // spike finding #2 + README in public/fonts/pdf/ for the rationale.
  Font.register({
    family: 'Source Sans 3',
    fonts: [
      { src: pdfFontPath('SourceSans3-Regular.ttf'), fontWeight: 400 },
      { src: pdfFontPath('SourceSans3-Semibold.ttf'), fontWeight: 600 },
    ],
  });

  registered = true;
}
